# Generated by Django 4.2.6 on 2023-10-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideratest', '0002_testresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresponse',
            name='question1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testresponse',
            name='question10',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testresponse',
            name='question11',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testresponse',
            name='question12',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testresponse',
            name='question13',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testresponse',
            name='question14',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testresponse',
            name='question15',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testresponse',
            name='question16',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testresponse',
            name='question17',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testresponse',
            name='question18',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testresponse',
            name='question2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testresponse',
            name='question3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testresponse',
            name='question4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testresponse',
            name='question5',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testresponse',
            name='question6',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testresponse',
            name='question7',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testresponse',
            name='question8',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testresponse',
            name='question9',
            field=models.TextField(),
        ),
    ]
