# Generated by Django 4.2.6 on 2023-10-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideratest', '0005_remove_knowledge_base_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge_base',
            name='id',
        ),
        migrations.AddField(
            model_name='knowledge_base',
            name='id_kbase',
            field=models.AutoField(db_column='id', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
