# Generated by Django 4.2.6 on 2023-10-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideratest', '0008_alter_myuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='type_user',
            field=models.BooleanField(default=False),
        ),
    ]
