# Generated by Django 4.2.6 on 2023-10-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideratest', '0009_alter_myuser_type_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='type_user',
            field=models.IntegerField(default=0),
        ),
    ]
