# Generated by Django 4.2.6 on 2023-10-25 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lideratest', '0012_alter_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='viewers',
        ),
        migrations.CreateModel(
            name='ResultadoLiderazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('calificaciones', models.JSONField()),
                ('resultado_final', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
