# Generated by Django 4.2.6 on 2023-10-26 11:00

from django.db import migrations, models
from lideratest.models import knowledge_base
def cargar_datos_iniciales(apps, schema_editor):
    knowledge_base_model  = apps.get_model('lideratest', 'knowledge_base')
    
    # Crear instancias de KnowledgeBase y guardar en la base de datos
    knowledge_base_model .objects.create(question="Animo a los miembros de mi equipo a participar en la toma de decisiones y trato de implementar sus ideas y sugerencias.")
    knowledge_base_model .objects.create(question="Nada es más importante que completar un objetivo tarea.")
    knowledge_base_model .objects.create(question="Monitoreo muy de cerca la duración de las tareas para asegurarme que serán completadas a tiempo.")
    knowledge_base_model .objects.create(question="Me gusta ayudar a los demás a realizar nuevas tareas o procedimientos.")
    knowledge_base_model .objects.create(question="Entre más desafiante es la tarea, más lo disfruto.")
    knowledge_base_model .objects.create(question="Animo a mis colaboradores a ser creativos en su trabajo.")
    knowledge_base_model .objects.create(question="Cuando miro una situación o tarea compleja ha sido completada me aseguro de todos los detalles.")
    knowledge_base_model .objects.create(question="Me es fácil llevar a cabo varias tareas complicadas al mismo tiempo.")
    knowledge_base_model .objects.create(question="Disfruto leyendo artículos, libros o revistas acerca de capacitación, liderazgo y psicología, y luego lo pongo en práctica.")
    knowledge_base_model .objects.create(question="Cuando corrijo errores no me preocupan las relaciones personales.")
    knowledge_base_model .objects.create(question="Yo administro mi tiempo con efectividad.")
    knowledge_base_model .objects.create(question="Me gusta explicar los detalles de una tarea compleja a mis empleados.")
    knowledge_base_model .objects.create(question="Dividir grandes proyectos en pequeñas tareas manejables es como una segunda naturaleza para mí.")
    knowledge_base_model .objects.create(question="No hay nada más importante que desarrollar un gran equipo de trabajo.")
    knowledge_base_model .objects.create(question="Me gusta analizar problemas.")
    knowledge_base_model .objects.create(question="Respeto los límites de los demás.")
    knowledge_base_model .objects.create(question="Aconsejar a mis empleados para que mejore su desempeño es mi naturaleza.")
    knowledge_base_model .objects.create(question="Disfruto leyendo artículos, libros y revistas acerca de mi profesión y luego implemento los procedimientos que he aprendido.")

class Migration(migrations.Migration):

    dependencies = [
        ('lideratest', '0013_remove_task_viewers_resultadoliderazgo'),
    ]

    operations = [
        migrations.AddField( 
            model_name='knowledge_base',
            name='id_kbase',
            field=models.AutoField(auto_created=True, db_column='id', primary_key=True, serialize=False),
            
        ),
        migrations.RunPython(cargar_datos_iniciales),
    ]
