# Generated by Django 4.2.6 on 2023-10-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideratest', '0015_alter_knowledge_base_id_kbase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge_base',
            name='id_kbase',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
