# Generated by Django 4.2.6 on 2023-10-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideratest', '0016_alter_knowledge_base_id_kbase'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoliderazgo',
            name='total_orientacion_personas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultadoliderazgo',
            name='total_orientacion_produccion',
            field=models.IntegerField(default=0),
        ),
    ]
