# Generated by Django 4.2.6 on 2023-10-28 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lideratest', '0017_resultadoliderazgo_total_orientacion_personas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='knowledge_base',
            name='id_kbase',
            field=models.AutoField(db_column='id', default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='myuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resultadoliderazgo',
            name='total_orientacion_personas',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='resultadoliderazgo',
            name='total_orientacion_produccion',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuarios_habilitados', models.ManyToManyField(related_name='clases_habilitadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
