# Generated by Django 4.2.6 on 2023-10-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideratest', '0019_resultadosevaluador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultadosevaluador',
            old_name='usuario',
            new_name='evaluador',
        ),
        migrations.RenameField(
            model_name='resultadosevaluador',
            old_name='resultado',
            new_name='resultado_final',
        ),
        migrations.AlterField(
            model_name='resultadosevaluador',
            name='total_orientacion_personas',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='resultadosevaluador',
            name='total_orientacion_produccion',
            field=models.FloatField(),
        ),
    ]
