# Generated by Django 4.2.6 on 2023-10-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideratest', '0020_rename_usuario_resultadosevaluador_evaluador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadosevaluador',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
