# Generated by Django 4.2.6 on 2023-11-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideratest', '0022_resultadosevaluador_suma_orientacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadosevaluador',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
