# Generated by Django 4.2.6 on 2024-01-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideratest', '0023_resultadosevaluador_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='job',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='need_complete',
            field=models.BooleanField(default=False),
        ),
    ]
