# Generated by Django 4.2.6 on 2024-01-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lideratest', '0024_myuser_job_myuser_need_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='job',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='need_complete',
        ),
    ]
