# Generated by Django 4.2.6 on 2024-01-31 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lideratest', '0026_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
