# Generated by Django 4.2.6 on 2024-01-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideratest', '0027_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='academy_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='myuser',
            name='job',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='myuser',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
